version: '3.7'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: note_manager
    ports:
      - 5432:5432
    volumes:
      - ../docker-data/postgres:/data 